### ISSUE TITLE
completed! here were some suggestion

### ISSUE THREAD

**Issue by hatelove** [johnwu1114/Homework#1]
建議一開始不要把所有測試案例都寫上，但的確應該瞭解完整的需求。

原因是一個測試案例，想辦法用最簡單的方式通過它，可以簡化我們的思緒，避免複雜化的思考。把需要考慮全盤的動作，放到重構的步驟。屆時怎麼小範圍、大規模的重構，都不用擔心，因為已經有測試保護。而且影響的範圍其實通常不大，要調整的 code 才不會在那邊大來大去。

算是第一個完成的，最主要的建議還是避免一開始把所有測試案例寫上去，多餘的紅燈會造成干擾，也會造成寫 prod code 想一鼓作氣搞定腦袋裡面的「需求」，而不是「只要管通過新的測試案例」即可。

**Comment by johnwu1114** [comment]
感謝老師建議，學生獲益良多。
今天順便把UI跟Web Test完成了，遇到了一點小問題，就是很想在Web Test用迴圈，想請問老師意見。
註記在PotterShoppingCart.Tests\HomeIndexPage.cs。

**Comment by hatelove** [comment]
review 完畢了，請看後面 commit history 的 comment。

完成度相當高，真要說只剩下 page object 的「domain 行為意義」抽象的部分，可以再練習一下。

我要 close 這個 issue 代表你 homework 已經完成了，而且你是目前第一個把這個 homework 連 web test 都做上去的學員。

**Comment by johnwu1114** [comment]
還沒貫通TDD精髓，又先寫網頁才寫Web Test，日後會銘記在心。
非常感謝老師的指導。
